//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeEffortCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<int> FROMID { get; set; }
        public Nullable<int> TOID { get; set; }
        public System.DateTime Date { get; set; }
        public string MESSAGE { get; set; }
        public bool ISREAD { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public int ProjectId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual Project Project { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual NotificationType NotificationType { get; set; }
    }
}
