//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeEffortCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Access = new HashSet<Access>();
            this.Workload = new HashSet<Workload>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal ContractUSD { get; set; }
        public decimal ContractUZS { get; set; }
        public int ManagerID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
        public string CType { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual ICollection<Access> Access { get; set; }
        public virtual ICollection<Workload> Workload { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
