//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeEffortCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workload
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public int ProjectID { get; set; }
        public decimal Duration { get; set; }
        public bool Approved { get; set; }
        public string Note { get; set; }
        public int WorkloadTypeID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual WorkloadType WorkloadType { get; set; }
    }
}
